### ISSUE TITLE
error - jsdom NodeList has no method 'map'

### ISSUE THREAD

**Issue by inconduit** [fuseelements/ember-brunch-skeleton#1]
hi, i know this is totally not an issue specific to your project but i've hit a wall with trying to get brunch test running on your awesome skeleton project.  below is the error i get when i try to run brunch test.  i have all of the dependencies installed, and put one simple spec file in the models dir.

is this error indicative of something very simple that i'm missing?  

TypeError: Object [ jsdom NodeList ]: contains 3 items has no method 'map'
  at getScriptFilesPath (/usr/local/lib/node_modules/brunch/lib/commands/test.js:62:60)
  at readTestFiles (/usr/local/lib/node_modules/brunch/lib/commands/test.js:80:25)
  at fs.readFile (fs.js:176:14)
  at fs.close     (/usr/local/lib/node_modules/brunch/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:90:5)
  at Object.oncomplete (fs.js:297:15)

**Comment by jonbuffington** [comment]
Can you provide me a copy of your test file?
